name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.5.0
    steps:
    - uses: actions/checkout@v2
    - name: Install rsync [required by gh-pages action]
      run: apt-get update && apt-get install -y rsync
    - name: Install dependencies
      run: shards install
    - name: Check formatting
      run: crystal tool format --check src spec
    - name: Crystal Ameba Linter
      uses: crystal-ameba/github-action@v0.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Unit tests
      run: crystal spec --verbose
    - name: Build docs
      run: crystal docs
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: docs
